### ISSUE TITLE
Have a climb animation to be out of the box compatible with platformers

### ISSUE THREAD

**Issue by PinoEire** [hippogamesunity/HeroEditor4DHub#1]
Platformers engines like Corgi expect to have a climb animation for stairs and similar. This would make this package out of the box usable with Corgi Engine. Next step would be full Corgi compatibility (at Animator level) which would be really awesome 😸

**Comment by hippogamesunity** [comment]
Hi! How does Corgi control the transition to Climb? Sorry, I don't have Corgi yet, but I want to make our animation flow compatible with it.

**Comment by PinoEire** [comment]
Corgi has its own animator and that manages everything. Here the screenshot with the animations managed by Corgi:
https://i.gyazo.com/c79052bd1386a44d595a85f2b5f261ba.png

**Comment by hippogamesunity** [comment]
And what are animation transition conditions? I mean animation parameters.

**Comment by PinoEire** [comment]
They vary, here a few of them:
https://i.gyazo.com/064accf74cbeffe64df1a4b2f68c563e.png
https://i.gyazo.com/ae37bb658935d2377d391c94a2e5b3f9.png
https://i.gyazo.com/7037d06919fd8df221686959e57ec512.png
https://i.gyazo.com/312ad9c8ad7939a2fb7efaa0e1b73f5f.png
https://i.gyazo.com/09f9b3f16b8d9431748a31ee19622014.png

**Comment by hippogamesunity** [comment]
Comes with update 1.1 (soon).
