### ISSUE TITLE
Animation/Movement with the 4D character models

### ISSUE THREAD

**Issue by KarmaBiscuit** [hippogamesunity/HeroEditor4DHub#11]
So I just recently go into making my own game and fell in love with the art style of the 4D character sprites. And I know how to create working animations and movements for a sprite through a sprite sheet and the animation/animator tabs. However I can't figure out how to work around not having a sprite sheet. If anyone has any words of advice or anything that works for them I'd love to know. Thanks

**Comment by hippogamesunity** [comment]
Hi! We don't have Sprite Sheet Maker yet. You can refer to Unity animation tutorials to learn how to deal with animations.

**Comment by KarmaBiscuit** [comment]
I appreciate the quick response, However that is an extremely broad answer I've been watching/reading animation tutorials for days. And have yet to find anything very helpful about how to turn the prefab that the editor gives you into a proper moveable, and animated character other than all four directions of the sprite moving simultaneously and only one direction working for animations at a time. Do you have any specific tutorials you were talking about?

**Comment by hippogamesunity** [comment]
I don't make tutorials, sorry. Unity provides a lot of tutorials about engine features, you can find them on YouTube.
Use Character4D.SetDirection to show only a singe direction.
