### ISSUE TITLE
SpriteSheetMaker Scene in Unity

### ISSUE THREAD

**Issue by mrsqurriel** [hippogamesunity/HeroEditor4DHub#12]
The documentation refers to a SpriteSheetMaker Scene. I tried searching the project. It does say to contact the developers if this feature is needed. I'm just trying to export spritesheets for the characters.

Thanks for the help.

**Comment by hippogamesunity** [comment]
Hi! This feature is not implemented yet.

**Comment by hippogamesunity** [comment]
Implemented!
