### ISSUE TITLE
SceneToCreateCharacter

### ISSUE THREAD

**Issue by MatteoCordioli99** [hippogamesunity/HeroEditor4DHub#13]
Here there is the point 8 of your manual:
8 SETUP & TEST GUIDE 
1. Download and install unity package 
2. Make sure you have HeroEditor4D folder added to your project 
3. Open HeroEditor4D/FantasyHeroes/Scenes/CharacterEditor scene 
4. Run the scene 
I can't find the folder HeroEditor4D/FantasyHeroes/Scenes when I import your package! I have no idea on what is going wrong, and without it how i create my character...
Ty for helping!

**Comment by hippogamesunity** [comment]
![image](https://user-images.githubusercontent.com/7318172/74243733-4e237f80-4cf1-11ea-8651-4835c3aaa46e.png)
