### ISSUE TITLE
SpriteCollection.dll set folder path

### ISSUE THREAD

**Issue by torokpeter** [hippogamesunity/HeroEditor4DHub#14]
It might be me, but I can't seem to set the path I want in the SpriteCollection "ScanFolderTags" list.
What i mean is that I want to change the path of my folders to follow my own structures and build my own hierarchy, but it seems that the SpriteCollection only searches for tags within the "HeroEditor4D" folder. Is there a way to specify a path such as "/Assets/Characters/Sprites" or something like this.

**Comment by hippogamesunity** [comment]
Hi! No, it's not possible to change the asset structure. All sprites should be inside HeroEditor4D.

**Comment by torokpeter** [comment]
Thank you for your super fast reply! :) I will work with that then.
