### ISSUE TITLE
Load from json ears not colored

### ISSUE THREAD

**Issue by Moelanz** [hippogamesunity/HeroEditor4DHub#15]
![afbeelding](https://user-images.githubusercontent.com/50054674/75851398-d88b6a80-5de9-11ea-8610-88edd37a0c40.png)

When saving to json and loading from that json the goblin ears Goblin/Goblin#73B479FF are not colored (Human ears are) maybe other goblin ears are also bugged ( not tested ).

This is the json:
`{"Body":"Basic/HumanPants#73B479FF","Ears":"Goblin/Goblin#73B479FF","Hair":"Basic/BroFlow#5D98FFFF","Beard":null,"Helmet":null,"Glasses":null,"Mask":null,"Armor":null,"PrimaryMeleeWeapon":null,"SecondaryMeleeWeapon":null,"Cape":null,"Back":null,"Shield":null,"Bow":null,"Crossbow":null,"WeaponType":"Melee1H","Expression":"Default","HideEars":"False","CropHair":"False","Expression.Default.Eyebrows":"Emoji/SadEyebrowns","Expression.Default.Eyes":"Goblin/Type1Angry#FF7878FF","Expression.Default.Mouth":"Basic/Mouth05","Expression.Angry.Eyebrows":null,"Expression.Angry.Eyes":null,"Expression.Angry.Mouth":null,"Expression.Dead.Eyebrows":null,"Expression.Dead.Eyes":null,"Expression.Dead.Mouth":null}`

**Comment by Moelanz** [comment]
Any update on this?

**Comment by hippogamesunity** [comment]
Hi! Will check this soon, sorry.

**Comment by hippogamesunity** [comment]
Fixed in version 1.8. Also make a backup of your project as there are a lot of changes we've made in the asset.

**Comment by Moelanz** [comment]
Thanks!

Can you maybe point out where you fixed this? So I can update only the
needed parts for this. I have overwritten allot of logic. Don't think I'll
need the other changes.

Op wo 22 apr. 2020 10:57 schreef Nate River <notifications@github.com>:

**Comment by hippogamesunity** [comment]
It's CharacterSerializerExperimental.cs script. But there also were some changes in character's structure.
