### ISSUE TITLE
Saving Prefab or JSON outside of default directory causes DirectoryNotFoundException

### ISSUE THREAD

**Issue by collierscott** [hippogamesunity/HeroEditor4DHub#16]
When trying to save Prefab or JSON, I get the following error:

```
DirectoryNotFoundException: Could not find a part of the path "C:\Users\scoll\OneDrive\GameDevelopment\Games\Unity\HippoCharacters\AssetsC:\Users\scoll\OneDrive\GameDevelopment\GameSprites\GenericHero.json".
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.
```

I can save if I use ```Assets\HeroEditor4D\FantasyHeroes\Prefabs```.

This is same for both Cahracter Editors (FH and Goblins). ANd, I am running in Unity.

Thanks

**Comment by hippogamesunity** [comment]
Hi! You should refer to Save method to learn what correct path can be used.
![image](https://user-images.githubusercontent.com/7318172/82732775-fea11680-9d17-11ea-8a93-2f82d4db1a60.png)

**Comment by hippogamesunity** [comment]
As you see you can't manage save process to save outside of project folder.
