### ISSUE TITLE
Everything goes white when I click Play

### ISSUE THREAD

**Issue by phobia77** [hippogamesunity/HeroEditor4DHub#18]
I'm using 2020.1 - is that a problem? Apologies if I'm doing something silly. 

![white](https://user-images.githubusercontent.com/3971972/89370763-e0e32b00-d724-11ea-8bd7-14633e244b44.JPG)

**Comment by phobia77** [comment]
Any response here please?

**Comment by luizhm0reira** [comment]
Hi, you need to mark the option "Include in Build" for the UI atlas. at least for me this worked.
![image](https://user-images.githubusercontent.com/18145524/91662352-ccc9e980-ea96-11ea-9a83-479ef5d32213.png)
