### ISSUE TITLE
Check if JSON serialization works

### ISSUE THREAD

**Issue by hippogamesunity** [hippogamesunity/HeroEditor4DHub#19]

**Comment by hippogamesunity** [comment]
This feature will be fixed with the next update. The current workaround:
1) Remove !Reference filter and refresh SpriteCollection
2) Comment lines 37-39 and 76-78 in CharacterSerializerExperimental.cs
![image](https://user-images.githubusercontent.com/7318172/97086898-d606ab00-162e-11eb-8289-e3e564e3bd8f.png)

**Comment by lianappdeveloper** [comment]
Hippo any date for this bug?

**Comment by hippogamesunity** [comment]
Hope November update will bring this.

**Comment by hippogamesunity** [comment]
Fixed!
