### ISSUE TITLE
Hard coded sorting layer breaking compatibility

### ISSUE THREAD

**Issue by PinoEire** [hippogamesunity/HeroEditor4DHub#2]
It seems that the DLL forces a specific sorting layer. This breaks the games because it's using a layer Id instead of a layer name. This should look for the sorting layer "Player"  and use that, otherwise, it should let the user set the preferred sorting layer.

**Comment by hippogamesunity** [comment]
I believe LayerManager.cs is a public script. It controls layers (manually from Editor). More details would be good.

**Comment by hippogamesunity** [comment]
Actually the basic idea is that only Editor scene code is hidden in DLL. Most of character related code is public.

**Comment by PinoEire** [comment]
I see, indeed setting manually the sorting layer on the prefab root and assigning the head manually to the four sides does work. I suppose not assigning all when the prefab is created is a bug?

**Comment by hippogamesunity** [comment]
You should call LayerManager after creating character instances (if needed).
