### ISSUE TITLE
V2.3 assignment errors and "SpriteCollection is null!" exception

### ISSUE THREAD

**Issue by edougithub** [hippogamesunity/HeroEditor4DHub#23]
After loading the character editor scene, there are several assignment errors:

![image](https://user-images.githubusercontent.com/29945804/101917412-81ac9000-3bc8-11eb-832a-ae0e07af21d3.png)

Saving/loading json creates exception :
Exception: SpriteCollection is null!
Assets.HeroEditor4D.Common.CharacterScripts.Character.ToJson () (at Assets/ThirdParty/HeroEditor4D/Common/CharacterScripts/CharacterSerializerExperimental.cs:16)
Assets.HeroEditor4D.Common.CharacterScripts.Character4D.ToJson () (at Assets/ThirdParty/HeroEditor4D/Common/CharacterScripts/Character4D.cs:52)
Assets.HeroEditor4D.Common.EditorScripts.CharacterEditor.SaveToJson () (at Assets/ThirdParty/HeroEditor4D/Common/EditorScripts/CharacterEditor.cs:276)
UnityEngine.Events.InvokableCall.Invoke () (at <a9810827dce3444a8e5c4e9f3f5e0828>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <a9810827dce3444a8e5c4e9f3f5e0828>:0)
UnityEngine.UI.Button.Press () (at C:/Program Files/Unity/Hub/Editor/2020.1.6f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/Program Files/Unity/Hub/Editor/2020.1.6f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/Program Files/Unity/Hub/Editor/2020.1.6f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/Program Files/Unity/Hub/Editor/2020.1.6f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at C:/Program Files/Unity/Hub/Editor/2020.1.6f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:376)

![image](https://user-images.githubusercontent.com/29945804/101917859-f97aba80-3bc8-11eb-9d74-7b8a1f9a7d13.png)

**Comment by edougithub** [comment]
Seems the Human prefab has the gameobjects Right -> Armor, Head, etc... set to SpriteMapping -> SpriteName = "Right". Shouldn't these be "Left"? (similar to the Goblin prefab)

**Comment by hippogamesunity** [comment]
Hello! Looks like this may be caused by update. Try removing and reimporting the asset.
I've checked the latest vesion from the Asset Store in the latest Unity, and it works fine.

**Comment by edougithub** [comment]
As a test I created a new empty 2D Unity 2020 project, only added this asset. It seems the Right Character is back, yeah! And the console errors are gone. However the Canvas is now completely white, any idea what could be the cause?
The Atlases looks correct as well as the Scene view. No changes to the scene were made at all.

![image](https://user-images.githubusercontent.com/29945804/101956106-56916300-3bff-11eb-827a-34b749dbdd69.png)

![image](https://user-images.githubusercontent.com/29945804/101956312-aa9c4780-3bff-11eb-8c8a-8931fef1e3f0.png)

**Comment by hippogamesunity** [comment]
Select HeroEditor4D\FantasyHeroes\Atlases\UI.atlas and check Include in Build (if you really need it for your game).

**Comment by edougithub** [comment]
Thanks for the assistance.

**Comment by hippogamesunity** [comment]
See ya! Also hope to get your feedback on the Asset Store!
