### ISSUE TITLE
[request] More feminine and gender neutral hair sprites

### ISSUE THREAD

**Issue by Amoo0001** [hippogamesunity/HeroEditor4DHub#24]
Currently there are **30** different hair sprites included with this asset with the following breakdown **based on my own personal opinion**:

- **27** of them (**90%**) are only suitable for a male or masculine character.
- **2** of them (**7%**) are only suitable for a female or feminine character.
- **1** of them (**3%**) is mostly only suitable for a female or feminine character, but could, for some characters, potentially be usable for a male or masculine character as well, maybe.
- **0** of them (**0%**) could be considered truly gender neutral in my opinion.

Please add many more feminine hair sprites so this asset can be just as usable for female characters as well.  If needed, I can provide examples of different feminine hairstyles that can be used for inspiration.

Please additionally add at least one or two good gender-neutral hairstyles.  I would like to have the default hairstyle for my game be as gender neutral as possible so as not to imply a default gender in my game's lore.

**Comment by officialstareye** [comment]
This is a great request. A few more feminine hairstyles and gender neutral would be perfect.

**Comment by hippogamesunity** [comment]
We're working on it!

ср, 24 февр. 2021 г., 07:49 thinkintermsofenergy <notifications@github.com>:
