### ISSUE TITLE
Getting two fatal errors on import

### ISSUE THREAD

**Issue by EmpireStudios** [hippogamesunity/HeroEditor4DHub#26]
Hi I get two errors when importing into Unity 2019.4.18f1

            ColorPicker.Color = _original = selected;
            ColorPicker.OnColorChanged = PickColor;

Assets\HeroEditor4D\Common\EditorScripts\CharacterEditor.cs(350,25): error CS1061: 'ColorPicker' does not contain a definition for 'Color' and no accessible extension method 'Color' accepting a first argument of type 'ColorPicker' could be found (are you missing a using directive or an assembly reference?)

Assets\HeroEditor4D\Common\EditorScripts\CharacterEditor.cs(351,25): error CS1061: 'ColorPicker' does not contain a definition for 'OnColorChanged' and no accessible extension method 'OnColorChanged' accepting a first argument of type 'ColorPicker' could be found (are you missing a using directive or an assembly reference?)

**Comment by hippogamesunity** [comment]
Hi, the asset was tested in Unity 2019. Try resolving other code issues, find name conflicts or just redownload the asset to a new empty project to make sure it works first.
