### ISSUE TITLE
But will the 'eyes' disappear from Android builds?

### ISSUE THREAD

**Issue by harrychae** [hippogamesunity/HeroEditor4DHub#27]
The unity3d editor 'eye' looks good.
But will the 'eyes' disappear from Android builds?
![photo_2021-07-26_19-40-19](https://user-images.githubusercontent.com/25000973/126980050-45468f36-468a-4443-81d8-f419ff484656.jpg)
<img width="1178" alt="스크린샷 2021-07-26 오후 8 14 46" src="https://user-images.githubusercontent.com/25000973/126980462-53ff5c4b-a9d0-4f0d-9e8e-85453cb1638b.png">
<img width="1673" alt="스크린샷 2021-07-26 오후 8 19 27" src="https://user-images.githubusercontent.com/25000973/126980917-62d984ef-d40b-4d1d-b1f5-707fa49e12e1.png">

**Comment by hippogamesunity** [comment]
Hi, just refer to FAQ. Also make sure that the atlas with eye sprites is incuded to build.

**Comment by harrychae** [comment]
Thank you. :)
The problem has been completely resolved.
-----------------------------------------------------------
Make sure you've set Auto Graphic API (Player Settings).
