### ISSUE TITLE
More animations needed

### ISSUE THREAD

**Issue by PinoEire** [hippogamesunity/HeroEditor4DHub#3]
In a fully-fledged platform game (and even more in an RPG isometric game!) one needs more animations, like two separate attacks a proper jump and a proper fall, a crouch ad crawl version of all the animations, a jetpack fly as well as wall climbing and wall jumping, a swim and a dive animations plus an edge cling with related movements. Also aiming of the weapons and look up and down are quite commonplace.

**Comment by luizhm0reira** [comment]
The climb animation for front is missing, can you add please? 
Thank you

**Comment by JosephB-one** [comment]
Please add the climbing and jumping animations to the sprite sheet for other engines.

**Comment by hippogamesunity** [comment]
Jump and Climb animations added to Capture Options in the Steam version 1.09, scheduled for the next update of the Unity version.

**Comment by JosephB-one** [comment]
That will be great. On discord it is mentioned that update 1.09 has been published, but when I check the asset store, the update included is 5.8 for female clothing. I imported that update, but there are no additional animations for the sprite sheet for jump or climbing.

Thanks,

Joe
________________________________

**Comment by hippogamesunity** [comment]
It was the Steam version. The unity version will be updated soon.
