### ISSUE TITLE
assign EyesRenderer and EyesbrowsRenderer

### ISSUE THREAD

**Issue by yobonill** [hippogamesunity/HeroEditor4DHub#37]
Hey, Oleg, I'm trying to make a button that resets the character to some default appearance, I'm using the file CharacterAppearance.cs as an example since it looks like that file does exactly that.

But, I'm receiving a console error stating that I probably need to assign EyesRenderer and EyesbrowsRenderer in the inspector.

I was looking at your example in the FantasyHeroes Scene, but you never reset character appearance, just wearable stuff
![unknown](https://user-images.githubusercontent.com/8281188/142764448-6d4adf35-8fc6-4500-af94-3cde740f36d4.png)

I didn't check if there were any other unassigned errors with the CharacterAppearance file example. If you need any other additional information let me know.

**Comment by hippogamesunity** [comment]
Hi! How can I reproduce this error? There is currently not way to reset appearance rather that restoring it from json or instantiating a new character.

ResetEquipment removes all equipment from a character. You can't do the same for appearance, unless you want to get a characer with no face.

**Comment by yobonill** [comment]
You can use the CharacterAppearance.cs as a reference. Is the one I'm using.

There you set "default" values for each body part, then you try to set up each part with those values.

If you want to reproduce that, you only need to call the Setup function in that file, passing the character reference. That throws the error.

![image](https://user-images.githubusercontent.com/8281188/143684772-50cf6dd3-7347-4cac-b469-32df2cee8c61.png)

Maybe I'm doing something wrong, I'm not an expert, learning in the process

**Comment by hippogamesunity** [comment]
This should fix it:

![image](https://user-images.githubusercontent.com/7318172/143685012-830a4446-7c29-4b97-a212-959caca28ae2.png)

![image](https://user-images.githubusercontent.com/7318172/143685004-290571da-74a4-4dc2-8182-699590ced9da.png)

**Comment by yobonill** [comment]
Let me try it right now.. give me a few minutes (just in case this is necessary to know):

So, What Am I exactly trying to do?

I just want to create a character that can be modified by the user, (without armors and weapons), just let the user change the appearance of their character, save those values, and assign them to their character within the game (in another scene).

I already do this with armors and weapons, I love your asset, I will be using them in most of my future games.

**Comment by yobonill** [comment]
Ready!!..

I added a reset for the beard since it is not there (character.Beard = null;).

Now that I see your code, I understand where the problem was, which means I will be able to change anything now.

This issue is solved :)
