### ISSUE TITLE
Epic extension not available in the editor scene

### ISSUE THREAD

**Issue by yobonill** [hippogamesunity/HeroEditor4DHub#39]
The IconCollection and the SpriteCollection, both have the corresponding folder added

But, if you go to "Armor" in the Sprite Collection or to "Icons" in the Icon Collection. They don't have the Epic extension added. 

![unknown](https://user-images.githubusercontent.com/8281188/150694609-d23362e9-d4ee-4c88-8959-4b372e1653d4.png)

![unknown](https://user-images.githubusercontent.com/8281188/150694615-ce1899c3-1736-4b78-a018-b03b35e30be2.png)

If you see here, there is an Acorn armor, that is not listed inside the Armor List. Same for the others inside the Epic extension.

![unknown](https://user-images.githubusercontent.com/8281188/150694615-ce1899c3-1736-4b78-a018-b03b35e30be2.png)

There are no updates pending for the asset*

**Comment by hippogamesunity** [comment]
Did you press the Refresh button on these collections? I can see these armors in the current version, also they exist in the demo https://hippogames.itch.io/fantasyheroes4d

**Comment by yobonill** [comment]
Hello... I did a refresh... it didn't work, but I decided to check the asset in the package manager again and saw there was an update from December. Updated and it fixed the issue. Sorry to take your time, but it didn't appear the first time.

**Comment by hippogamesunity** [comment]
Glad to hear this, good luck!
