### ISSUE TITLE
Fresh Install: Newtonsoft.Json Not Found

### ISSUE THREAD

**Issue by benjaminb24** [hippogamesunity/HeroEditor4DHub#41]
Hi! Really looking forward to using this asset but unfortunately having issues that Google-fu is not fixing...
I have 54 errors out the gate importing this newly purchased asset. All related to not finding the import: Newtonsoft.Json;.

Google has walked me through using Nuget in Visual Studio to download Newtonsoft.Json, which I have. I first downloaded v13.0.1 and after this failed to clear up these alerts, I uninstalled and installed a version below (to check if it was a version thing. Ensuring that Nuget had Remove DEpendendancies and Force uninstall, even if there are dependencies on it options were checked.

All these attempts are just failing and I do not know where to go from here. I imagine it is something simple, but technical. Please assist at your earliest convenience.

**Comment by benjaminb24** [comment]
![image](https://user-images.githubusercontent.com/16454759/157388626-a4ed8204-3ee1-4747-8be7-0bbd407f6e7c.png)

**Comment by benjaminb24** [comment]
I've continued to mess with it and watched some more tutorials which only leaves me more lost. This package is installed and says it is in my project (nested in many other packages. However, it is saying that it cannot find it for all scripts that use it... any guidance would be amazing!

**Comment by hippogamesunity** [comment]
Hi, bro, just visit our FAQ on GitHub.

**Comment by royreiss** [comment]
I'm receiving the same messages.  I went to the settings for the included Newtonsoft.Json.dll and made sure it was included for the build, but I'm still receiving the errors.

![image](https://user-images.githubusercontent.com/4852279/157507191-3e559d56-3eac-4866-9a2d-86b017a4f2e6.png)

Did I misunderstand the FAQ or is there something else I should try?  Thanks!

**Comment by benjaminb24** [comment]
Thanks for responding, unfortunately, I am still having issues. Should I be uninstalled Newtonsoft from nuget and using the one provided in your download? Should I be removing the one you provided and depending on the new one?

I've confirmed that the package-lock file does not include the newtonsoft dependency as per the third bullet of the FAQ. Now the second and first bullet, I could use a bit more clarity on. (Ie, where do I check to find those packages? are they nested deep somewhere?)
![image](https://user-images.githubusercontent.com/16454759/157539670-806f6fdb-abc5-4045-b570-79c08f73906d.png)

**Comment by hippogamesunity** [comment]
Don't use nuget with Unity! Use any newtonsoft lib you want, and avoid duplicates, of course.

**Comment by benjaminb24** [comment]
tbh I'll need a bit more direction. I believe Nuget is visual studios default package manager. Should I be uninstalling Newtonsoft from there? Is that why you included the .dll in the commons folder of your package? Not sure how two copies ended up in the solutions explorer...

**Comment by hippogamesunity** [comment]
Yes, remove nuget. Unity overrides vs solution and generates it automatically.

**Comment by benjaminb24** [comment]
Hi hippogamesunity, I have uninstalled Newtonsoft.Json from Visual studios so now I am back at square one. The errors still persist. Do I need to move the .dll that you provided into a particular directory? Unity is still seeing the same errors as before.

**Comment by benjaminb24** [comment]
Please assist when you have a chance, not sure where the .dlls need to go in order for my visual studio to recognize them.

**Comment by hippogamesunity** [comment]
I don't understand where you stucked. Remove duplicated DLL if it's duplicated. Include DLL located in the asset if it's missed (check Include in Builds).

**Comment by benjaminb24** [comment]
Hi and thanks for responding.
Sorry again for any frustration my lack of knowledge is creating.

I have created a new project, fully uninstalled nuget as requested, and imported this package into this blank project.
There are 54 errors again.

![image](https://user-images.githubusercontent.com/16454759/158331644-b15a6e1d-5257-4444-9b39-a34a9fcd3b97.png)

Can you tell me step by step what I need to do? Previously you said to add something to my "build". Can you confirm what general directory that is supposed to be? I do not want to make any attempts to change anything as I don't want to cause confusion.

**Comment by hippogamesunity** [comment]
Find the DLL inside the asset and check Include in Builds

**Comment by benjaminb24** [comment]
Roger, and by "include in Builds" what do you mean? How do I go about including that in builds? Do I need to move it somewhere?

**Comment by benjaminb24** [comment]
And to clarify, the issue I am having is I cannot run the unity editor to use the assets that I have purchased.

**Comment by hippogamesunity** [comment]
Select DLL and check Include in Builds, I don't have a PC right now to
show, sry.

вт, 15 мар. 2022 г., 12:36 benjaminb24 ***@***.***>:

**Comment by hippogamesunity** [comment]
Try refering to docs or YouTube for tutorials.

вт, 15 мар. 2022 г., 12:48 Hippo Games ***@***.***>:

**Comment by benjaminb24** [comment]
![image](https://user-images.githubusercontent.com/16454759/158359149-841d4857-49d3-438c-82d1-627d7603d8ae.png)

**Comment by benjaminb24** [comment]
![image](https://user-images.githubusercontent.com/16454759/158361007-1a541b96-623c-452d-a038-5721b281a4a6.png)

**Comment by benjaminb24** [comment]
Feel like I am getting closer but still running into hurdles. Youtube and Google are showing that I should be able to "Add the Reference DLL through Visual Studio". From the instructions on Unity's website/ VIsual Studios documentation/ and Youtube, everyone just right-clicks the References subdirectory in the solutions explorer then selects "Add Reference" But as you can see, all I am getting is Add Analyzer /facepalm

**Comment by benjaminb24** [comment]
Figured it out! For people that are having problem in the future: Open Visual Studio in the project you are working on (easy way is to select a script or double click on the unity error. Up at the top of Visual Studio Select Project > Add Reference > Find that DLL. Errors be gone!

Thanks for your help!

**Comment by benjaminb24** [comment]
Ugh, spoke to soon. Visual Studio is recognizing the import now but Unity is not getting the memo, still says there are issues although Visual Studio is saying everything is fine. Closed and re-opened both applications to no avail. Any advice?

**Comment by hippogamesunity** [comment]
![image](https://user-images.githubusercontent.com/7318172/158401104-47287053-aac4-44a9-a30b-3cb5897a373d.png)

**Comment by benjaminb24** [comment]
So weird, could've sworn those were unchecked and it didn't work and now unchecking them caused it to work... sorry to waste your time and greatly appreciate the help!

**Comment by hippogamesunity** [comment]
Don't worry, good luck and thanks for your review!
