### ISSUE TITLE
4D Animation Suggest

### ISSUE THREAD

**Issue by TimeToTheNorth** [hippogamesunity/HeroEditor4DHub#43]
The animation facing up should be waving the hand up instead of down. It currently looks more like a 3D motion

**Comment by hippogamesunity** [comment]
Hi, what do you mean?

чт, 29 дек. 2022 г., 11:08 时光向北 ***@***.***>:

**Comment by TimeToTheNorth** [comment]
HI I Want it like this
![9 9TK}MBSX ~CEJF )1DEM](https://user-images.githubusercontent.com/45864431/209932274-b8a375c0-5bd9-4436-af71-2f35d5bb96ae.png)

**Comment by hippogamesunity** [comment]
You can edit animations to fit your needs. We use Unity animation system, so you can just adjust animations inside Unity.
