### ISSUE TITLE
Impossible to save/load Vest, Bracers, Leggings as JSON

### ISSUE THREAD

**Issue by il-shunder** [hippogamesunity/HeroEditor4DHub#44]
When I select Vest, Bracers, Leggings from different outfits (f.e. Pilot Vest, Police Bracers, Cowboy Leggings) and click "Save As Json", it only saves the Armor no matter what is selected in the Vest, Bracers, Leggings tabs. And so when I click "Load From Json" it only loads Armor

I can make it to save Vest, Bracers, Leggings by adding the appropriate lines to the ToJson function in the Assets\HeroEditor4D\Common\Scripts\CharacterScripts\CharacterSerializer.cs file, but then there are problems in the LoadFromJson function

Need to make "Save As Json" and "Load From Json" work correctly with Vest, Bracers, Leggings
![image](https://user-images.githubusercontent.com/70568857/222717489-457336ce-edfc-47f8-b1ec-a31473c36ac9.png)

**Comment by hippogamesunity** [comment]
Hi, fixed in v5.2.

**Comment by il-shunder** [comment]
Hey @hippogamesunity 

Thank you for fixed that

Could you please explain what needs to be done to make it works correctly?

**Comment by hippogamesunity** [comment]
Just update the asset, there were changes in different files.
