### ISSUE TITLE
Issue with loading Firearm1H and Firearm2H from JSON

### ISSUE THREAD

**Issue by il-shunder** [hippogamesunity/HeroEditor4DHub#45]
When I try to load a character with Firearm1H or Firearm2H from JSON, it displays/renders it uncorrectly, also the fire animation doesn't work
![image](https://user-images.githubusercontent.com/70568857/227716306-003403ec-a961-4407-a058-4368474aceaa.png)

**Comment by hippogamesunity** [comment]
The fix will be available in the next update.

**Comment by il-shunder** [comment]
Hey @hippogamesunity 

Thank you for fixed that!

Could you please explain how to make it work correctly?

Also, do you know the approximate date of the next update?

**Comment by hippogamesunity** [comment]
We have to complete some other tasks planned for the next update. This may take a week maybe.

**Comment by il-shunder** [comment]
Hey @hippogamesunity 

so when will be the next release, since it's still 4.9 in the Unity Asset Store?

![photo_2023-04-30_16-41-08](https://user-images.githubusercontent.com/70568857/235356080-deb5861e-0d20-4905-9fb5-ea6b41480db6.jpg)

**Comment by hippogamesunity** [comment]
Hi, sorry for the delay. I've just updated it to 5.5.

**Comment by il-shunder** [comment]
Hey, thank you so much
