### ISSUE TITLE
RuntimeSetup.cs issue

### ISSUE THREAD

**Issue by tokochan55** [hippogamesunity/HeroEditor4DHub#5]
EquipHelmet doesn't work.
![08](https://user-images.githubusercontent.com/52799387/66118290-f7a28800-e610-11e9-983d-529a89105ce5.gif)
ex: EquipHelmet("VillagerRags","Basic");

**Comment by hippogamesunity** [comment]
Try this fix:
![image](https://user-images.githubusercontent.com/7318172/66118760-d83f3700-e5df-11e9-9211-5e81dd799192.png)

**Comment by tokochan55** [comment]
still doesn't work.
FindSprites is not found.
![2019-10-03_19h28_27](https://user-images.githubusercontent.com/52799387/66119739-3ede4800-e614-11e9-9aeb-8c880cd6e8b8.png)

**Comment by hippogamesunity** [comment]
Are you using the latest asset version? can you show me EquipArmor code?

**Comment by tokochan55** [comment]
yes. im using latest asset version.
i just reimport asset now but still doesn't work.
![2019-10-03_19h46_13](https://user-images.githubusercontent.com/52799387/66120741-8ebe0e80-e616-11e9-9c05-894d87cbf54e.png)

**Comment by hippogamesunity** [comment]
I will update the plugin soon. As a workaround try:
var sprites = "THE SAME CODE AS FOR ARMOR";
var sprite = sprites.Single(i => i.name == "FrontHead");

Character.EquipHelmet(sprite);

**Comment by tokochan55** [comment]
it worked! thank you so much. 
you are very kindness!

**Comment by hippogamesunity** [comment]
Great! Hope to see your feedback on the Asset Store!

**Comment by hippogamesunity** [comment]
1.5 is on review
