### ISSUE TITLE
need 4 direction monsters 

### ISSUE THREAD

**Issue by brucezhu99** [hippogamesunity/HeroEditor4DHub#6]
Dear Hippo,
I really like your art style  of the 4-direction hero editor plugin and want to use them in my game, but I can not find suitable monster-sprites for it, so , is there any chance you can design the 4-direction monsters editor in same style? If so, I will buy the both :-)
It will be better that you can also design the game backgrond editor for us, I really want to buy all of them!
Thanks!

**Comment by hippogamesunity** [comment]
Hello! We are making a new monster pack, not 4d. It will appear soon. You
can also find some backgrounds on our account, but we are not focused on
them.

вс, 27 окт. 2019 г., 13:23 brucezhu99 <notifications@github.com>:

**Comment by brucezhu99** [comment]
Tanks for your reply! It is very nice to hear the new monster pack. But there will be a little pity for no 4 direction monster to match your 4d hero editor, so we will find the other 4d monster later......

**Comment by hippogamesunity** [comment]
https://assetstore.unity.com/packages/2d/characters/fantasy-animated-monsters-159572
