### ISSUE TITLE
Cannot play the scene

### ISSUE THREAD

**Issue by iaftersmile** [hippogamesunity/HeroEditor4DHub#7]
I just installed Unity 2019.1.14f1 and import the asset. When I play test the scene I got the message " All the compiler errors have to be fixed before you can enter play mode".

![unity_prob](https://user-images.githubusercontent.com/23424263/67860490-89d67700-fb50-11e9-8072-47223df993fa.jpg)
I also got notification: RightLegL's rect lies (partially) outside of texture. Will not generate Sprite for this slice. 

I just noticed that I also got this for all the script: the associated script cannot be loaded. please fix all compile errors site:

**Comment by hippogamesunity** [comment]
- try the latest Unity version
- delete the asset and install the latest version from the Asset Store

I've just checked this sequence and it works just fine.
