### ISSUE TITLE
Keep hair & ears when applying helmets

### ISSUE THREAD

**Issue by Moe-Baker** [hippogamesunity/HeroEditor4DHub#9]
Hi,
We have created some custom sprites to use with your asset for our game, new armor, weapons, hair ... etc, these sprites are meant to be used to create our characters, characters who can have wear custom helmets, hair, and ears at the same time.
Currently, any character that has a helmet on will have their ears and hair set to a default sprite, this behavior is counter-productive to what we are trying to achieve, it would be great if you added a feature to fit our workflow, it seems like a reasonable feature that other people would take advantage of.

**Comment by hippogamesunity** [comment]
Use these tags in your sprite names, like CustomHelmet [ShowEars].png
![image](https://user-images.githubusercontent.com/7318172/69006207-c1109a80-093c-11ea-82f3-1fe8eebd6636.png)

**Comment by hippogamesunity** [comment]
Also you can change this logic, it's public script.

**Comment by Moe-Baker** [comment]
Thank you for the swift replay, commenting out the suggested lines fixed the ears issue and changing this line:
`HairRenderer.sprite = Helmet == null || Hair == null ? Hair : HairCut`
To
`HairRenderer.sprite = Hair`
Removes the restrictions on the hair as well
